name: Hello world workflow

on:
  push:
    branches:
      - main
    pull_request:
      - main
    workflow_dispatch:
  
job:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: hello wolrd
        run: echo "Hello world"
        shell: bash
    
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye world
        run: echo "Goodbye world"
        shell: bash


